# Generated by Django 3.1.6 on 2021-04-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hint1', models.TextField(blank=True, null=True)),
                ('hint2', models.TextField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('num_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['num_order'],
            },
        ),
        migrations.CreateModel(
            name='UserQrs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hints', models.IntegerField(blank=True, default=0)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimkana.qr')),
            ],
            options={
                'ordering': ['qr_id'],
            },
        ),
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scanned_by', models.CharField(default='user2', max_length=250)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('L', 'Locked'), ('U', 'Unlocked'), ('S', 'Scanned')], help_text='QR status', max_length=1, null=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_id', to='gimkana.qr')),
            ],
            options={
                'ordering': ['qr_id', 'scanned_by'],
                'unique_together': {('qr_id', 'scanned_by')},
            },
        ),
    ]
