# Generated by Django 3.1.6 on 2021-04-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hint', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('L', 'Locked'), ('U', 'Unlocked'), ('S', 'Scanned')], default='L', help_text='QR status', max_length=1)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_id', to='gimkana.qr')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['qr_id', 'scanned_by'],
                'unique_together': {('qr_id', 'scanned_by')},
            },
        ),
    ]
