# Generated by Django 3.1.6 on 2021-06-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimkana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
