# Generated by Django 3.1.6 on 2021-02-17 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gimkana', '0002_auto_20210217_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular QR scan', primary_key=True, serialize=False)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('L', 'Locked'), ('U', 'Unlocked'), ('S', 'Scanned')], default='L', help_text='QR status', max_length=1)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimkana.qr')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scan_date'],
            },
        ),
    ]
