# Generated by Django 3.1.6 on 2021-02-20 20:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gimkana', '0003_qrscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrscan',
            options={'ordering': ['qr', 'scanned_by']},
        ),
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together={('qr', 'scanned_by')},
        ),
    ]
