# Generated by Django 3.1.6 on 2021-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimkana', '0007_auto_20210311_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrscan',
            name='_id',
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
