# Generated by Django 3.1.6 on 2021-03-11 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gimkana', '0008_auto_20210311_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='scanned_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
