# Generated by Django 3.1.6 on 2021-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimkana', '0009_qr_scanned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='scanned_by',
        ),
        migrations.DeleteModel(
            name='UserQr',
        ),
    ]
